<?php

namespace Antevenio\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function getCountryById($id)
    {
        $query    = $this->getEntityManager()->createQuery('SELECT c FROM \Antevenio\Entity\Country c WHERE c.id = :id');
        $query->setParameters(array(
            'id' => $id,
        ));
        $country  = $query->getArrayResult();

        return isset($country[0]) ? $country[0] : null;
    }

    public function getAllCountries()
    {
        $query    = $this->getEntityManager()->createQuery('SELECT c FROM \Antevenio\Entity\Country c');
        return $query->getArrayResult();
    }
}
